inherit: true

filter:
    paths:
        - 'src/*'
        - 'lib/*'
    excluded_paths:
        - 'vendor/*'
        - 'cache/*'
        - 'tests/*'
        - 'Tests/*'
        - 'bin/*'
        - 'tmp/*'
        - 'vagrant/*'
        - 'resources/*'
        - 'config/*'
        - 'web/*'
build:
    environment:
        php: '5.4.10'
    dependencies:
        before:
            - "npm install -g dynalite"
            - "dynalite --createTableMs 10 --deleteTableMs 10 --updateTableMs 10 &"
            - "sleep 5"
            - "echo \"memory_limit = 1024M\" > ~/.phpenv/versions/$(phpenv global)/etc/conf.d/memory.ini"
            - "echo \"xdebug.max_nesting_level = 1000\" >> ~/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini"
            - "sed -i 's/^;//' ~/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini"
            - "cp app/config/parameters.yml.dist app/config/parameters.yml && composer install --dev --prefer-source"
        override:
            - true
    tests:
        override:
            -
                command: php -d memory_limit=256M bin/phpunit --coverage-clover=uniplaces -c app
                coverage:
                    file: uniplaces
                    format: php-clover


before_commands:
    - 'composer install --prefer-source'
    - 'git clone https://github.com/uniplaces/ci-configs.git /tmp/ci-configs'
checks:
    php:
        custom_coding_standard:
            git_repository: 'https://github.com/uniplaces/ci-configs.git'
            git_version: 'HEAD'
            ruleset_path: 'src/Uniplaces/Phpcs/ruleset.xml'

tools:
    php_sim:
        enabled: true
    # PHP Similarity Analyzer and Copy/paste Detector cannot be used at
    # the same time right now. Make sure to either remove, or disable one.
    php_cpd:
        enabled: false
    php_mess_detector:
        enabled: true
        command: phpmd
        config:
            ruleset: '/tmp/ci-configs/src/Uniplaces/Phpmd/ruleset.xml'
    sensiolabs_security_checker:
        enabled: true
    php_loc:
        enabled: true
        command: phploc
        excluded_dirs:
            - tests
            - test
            - Tests
            - Test
            - cache
            - bin
            - tmp
            - vagrant
            - resources
            - config
            - web
            - vendor
    php_pdepend:
        enabled: true
        command: pdepend
        excluded_dirs:
            - tests
            - test
            - Tests
            - Test
            - cache
            - bin
            - tmp
            - vagrant
            - resources
            - config
            - web
            - vendor
    php_analyzer:
        enabled: true
        filter:
            paths:
                - 'src/*'
                - 'lib/*'
            excluded_paths:
                - 'vendor/*'
                - 'cache/*'
                - 'tests/*'
                - 'Tests/*'
                - 'bin/*'
                - 'tmp/*'
                - 'vagrant/*'
                - 'resources/*'
                - 'config/*'
                - 'web/*'
        config:
            # Checks
            check_access_control:
                enabled: true
            basic_semantic_checks:
                enabled: true
            simplify_boolean_return:
                enabled: false
            dead_assignments:
                enabled: true
            typo_checks:
                enabled: true
            deadlock_detection:
                enabled: true
            check_usage_context:
                enabled: true
                foreach:
                    value_as_reference: true
                    traversable: true
                missing_argument: true
                argument_type_checks: strict
            phpunit_checks:
                enabled: true
            parameter_reference_check:
                enabled: true
            precedence_checks:
                enabled: true
                assignment_in_condition: true
                comparison_of_bit_result: true
            reflection_checks:
                enabled: true
            checkstyle:
                enabled: true
                no_trailing_whitespace: true
                naming:
                    enabled: false
            suspicious_code:
                enabled: true
                overriding_parameter: true
                overriding_closure_use: true
                parameter_closure_use_conflict: true
                parameter_multiple_times: true
                non_existent_class_in_instanceof_check: true
                non_existent_class_in_catch_clause: true
                assignment_of_null_return: true
                non_commented_switch_fallthrough: true
                non_commented_empty_catch_block: true
                overriding_private_members: true
                use_statement_alias_conflict: true
                precedence_in_condition_assignment: true
            unreachable_code:
                enabled: true
            check_variables:
                enabled: true
            # Fixes
            doc_comment_fixes:
                enabled: false
            reflection_fixes:
                enabled: false
            use_statement_fixes:
                enabled: false