#!/bin/bash
#
# @author Uniplaces Ltd.

verifyDir ()
{
prepareDir $DIR

if [[ ! -d "$DIR" ]]; then
    echo "$DIR is not a path"
    pwd
    exit 1
fi
}

prepareDir ()
{
if [[ ! "$DIR" = /*  ]]; then
    DIR=${DIR//..\//}
fi
}

DIR=$(dirname $(readlink $0))
verifyDir $DIR

if [ -L $DIR/prepare-commit-msg ]; then
    DIR=$(dirname $(readlink $DIR/prepare-commit-msg))
    verifyDir $DIR
fi


export DIR

### Circleci hook ###
. $DIR/Circleci/prepare-commit-msg




