#!/bin/bash
#
# @author Uniplaces Ltd.

verifyDir ()
{
prepareDir $DIR

if [[ ! -d "$DIR" ]]; then
    echo "$DIR is not a path"
    pwd
    exit 1
fi
}

prepareDir ()
{
if [[ ! "$DIR" = /*  ]]; then
    DIR=${DIR//..\//}
fi
}

DIR=$(dirname $(readlink $0))
verifyDir $DIR

if [ -L $DIR/pre-commit ]; then
    DIR=$(dirname $(readlink $DIR/pre-commit))
    verifyDir $DIR
fi

export DIR

### PHP_CodeSniffer hook ###
. $DIR/Phpcs/pre-commit




